# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('author', models.CharField(max_length=31)),
                ('release_date', models.DateField()),
                ('slug', models.SlugField()),
                ('genere', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('director', models.CharField(max_length=31)),
                ('release_date', models.DateField()),
                ('slug', models.SlugField()),
                ('genere', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('artist', models.CharField(max_length=31)),
                ('release_date', models.DateField()),
                ('slug', models.SlugField()),
                ('genere', models.CharField(max_length=31)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dvd',
            unique_together=set([('slug', 'name')]),
        ),
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='catalog.Dvd'),
        ),
    ]
