# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170302_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genere',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='genere',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='genere',
            new_name='genre',
        ),
    ]
